# -*- coding: utf-8 -*-
"""fibonacci.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19TesnJsRHVWhbdSwhVpjE_Li8Pzkj1EM
"""

n = 10
a, b = 0, 1
for i in range(n):
    print(a, end=" ")
    next_val = a + b
    a = b
    b = next_val
print()